import {createContext,useContext,useState,type ReactNode} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {api,type Conversation} from './api';
type Context={index_id?:string;backtest_id?:string};
type AgentState={open:boolean;setOpen:(v:boolean)=>void;active:string;setActive:(v:string)=>void;context:Context;draft:string;setDraft:(v:string)=>void;ask:(text:string,c?:Context)=>void;settings:boolean;setSettings:(v:boolean)=>void;config:{model:string;base_url:string;api_key:string};setConfig:(v:{model:string;base_url:string;api_key:string})=>void};
const AgentContext=createContext<AgentState>(null!);
export const useAgent=()=>useContext(AgentContext);
export function AgentProvider({children}:{children:ReactNode}){const [open,setOpen]=useState(false),[active,setActive]=useState(''),[context,setContext]=useState<Context>({}),[draft,setDraft]=useState(''),[settings,setSettings]=useState(false),[config,setConfig]=useState({model:'',base_url:'https://api.openai.com/v1',api_key:''});return <AgentContext.Provider value={{open,setOpen,active,setActive,context,draft,setDraft,settings,setSettings,config,setConfig,ask:(text,c={})=>{setContext(c);setDraft(text);setActive('');setOpen(true)}}}>{children}{settings&&<div className="overlay"><section className="modal"><div className="row"><h2>模型与 API 设置</h2><button className="btn" onClick={()=>setSettings(false)}>关闭</button></div><p>Key 仅保存在当前页面内存，刷新即清除。服务地址需要在后端允许范围内。</p><label>兼容 API 地址<input value={config.base_url} onChange={e=>setConfig({...config,base_url:e.target.value})}/></label><label>模型名称<input value={config.model} placeholder="填写服务支持的模型 ID" onChange={e=>setConfig({...config,model:e.target.value})}/></label><label>API Key<input type="password" autoComplete="off" value={config.api_key} onChange={e=>setConfig({...config,api_key:e.target.value})}/></label><button className="btn primary" onClick={()=>setSettings(false)}>完成</button></section></div>}</AgentContext.Provider>}
export function AgentPanel({drawer=false}:{drawer?:boolean}){const a=useAgent(),qc=useQueryClient();const [error,setError]=useState('');const history=useQuery({queryKey:['conversations'],queryFn:()=>api<Conversation[]>('/conversations')});const conversation=useQuery({queryKey:['conversation',a.active],queryFn:()=>api<Conversation>('/conversations/'+a.active),enabled:!!a.active});const send=useMutation({mutationFn:async({id,text,context}:{id:string;text:string;context:Context})=>{const target=id||(await api<Conversation>('/conversations',{title:text.slice(0,45)})).id;if(!id)a.setActive(target);try{const result=await api<Conversation>('/conversations/'+target+'/messages',{message:text,...a.config,context});qc.setQueryData(['conversation',target],result);return target}finally{void qc.invalidateQueries({queryKey:['conversation',target]});void qc.invalidateQueries({queryKey:['conversations']});void qc.invalidateQueries({queryKey:['strategies']});void qc.invalidateQueries({queryKey:['watchlist']});}},onError:e=>setError(e.message)});
 const submit=()=>{if(!a.draft.trim()||send.isPending)return;if(!a.config.model||!a.config.api_key){setError('请先填写模型名称和 API Key');a.setSettings(true);return}setError('');const text=a.draft;a.setDraft('');send.mutate({id:a.active,text,context:a.context})};
 return <section className={drawer?'agent-drawer':'panel agent-page'} role={drawer?'dialog':undefined} aria-modal={drawer||undefined} aria-label={drawer?'Agent 研究助手':undefined}><div className="panel-heading"><div><h2>✧ Agent 研究助手</h2><p className="muted">研究策略 · 创建策略 · 解读回测</p></div><div className="actions"><button className="btn small" onClick={()=>a.setSettings(true)}>模型设置</button>{drawer&&<button className="btn small" onClick={()=>a.setOpen(false)} aria-label="关闭 Agent">关闭</button>}</div></div><div className="agent-body"><div className="history"><button className="btn full" onClick={()=>{a.setActive('');a.setDraft('');setError('')}}>＋ 新对话</button>{history.error&&<p className="error">{history.error.message}</p>}{history.data?.map(c=><button key={c.id} className={'history-item '+(c.id===a.active?'selected':'')} onClick={()=>{a.setActive(c.id);a.setDraft('');setError('')}}>{c.title}<small>{new Date(c.created_at).toLocaleDateString('zh-CN')}</small></button>)}</div><div className="chat"><div className="messages" aria-live="polite">{conversation.error&&<p className="error">{conversation.error.message}</p>}{!a.active&&<div className="chat-welcome"><div className="big-icon">✧</div><h2>让每一步都有依据</h2><p>可读取项目行情、持仓与策略，调用工具创建策略，并基于保存的回测结果继续分析。</p><button className="btn" onClick={()=>a.setDraft('请帮我研究一个均线策略，说明假设、参数和风险，并创建策略。')}>帮我研究并创建策略</button></div>}{conversation.data?.messages?.map(m=><div key={m.id} className={'message '+m.role}><div className="bubble"><small>{m.role==='user'?'你':'Agent'}</small><div className="message-content">{m.content}</div>{m.tool_calls?.map((t,n)=><details className="tool-result" key={n}><summary>{t.name} · {t.status}</summary><pre>{JSON.stringify({参数:t.arguments,结果:t.result},null,2)}</pre></details>)}</div></div>)}{send.isPending&&<p className="muted">正在研究并执行工具，请稍候…</p>}{error&&<p className="error" role="alert">{error}</p>}</div>{Object.keys(a.context).length>0&&<div className="context-chip">已附带{a.context.backtest_id?'回测结果快照':'所选指数'}上下文</div>}<form className="chat-input" onSubmit={e=>{e.preventDefault();submit()}}><textarea aria-label="发送给 Agent" placeholder="向 Agent 提问，或要求创建策略…" value={a.draft} onChange={e=>a.setDraft(e.target.value)}/><button className="btn primary" disabled={send.isPending||!a.draft.trim()}>发送</button></form><div className="chat-disclaimer">工具过程保存在服务端会话中 · 不连接真实券商订单</div></div></div></section>}
